# Generated by Django 4.1.13 on 2024-08-22 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pensiune_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='PensiuneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pensiuni_images/')),
                ('pensiune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.pensiune')),
            ],
        ),
    ]
