# Generated by Django 4.1.13 on 2024-08-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pensiuneimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pensiune',
            name='image',
        ),
    ]
