# Generated by Django 4.1.13 on 2024-08-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_jobpost_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='employment_type',
            field=models.CharField(default='Full-Time', max_length=50),
        ),
    ]
