# Generated by Django 4.1.13 on 2024-08-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_userinterest_alter_jobpost_employment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='domain',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='employment_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='experience_level',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='skills',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
