# Generated by Django 4.1.13 on 2024-08-27 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_jobpost_created_at_alter_jobpost_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='created_by',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='languages',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='skills',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
