# Generated by Django 4.1.13 on 2024-08-29 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0016_remove_jobpost_updated_at_jobpost_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('skills', models.CharField(max_length=500)),
                ('experience_level', models.CharField(choices=[('Junior', 'Junior'), ('Mid-Level', 'Mid-Level'), ('Senior', 'Senior')], max_length=50)),
                ('preferred_location', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Freelance', 'Freelance'), ('Internship', 'Internship'), ('Remote', 'Remote')], max_length=50)),
                ('industry', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
