# Generated by Django 5.1 on 2024-09-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cv_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
