name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Create Lambda Layer
        run: |
          cd backend
          mkdir -p python
          pip install \
            --platform manylinux2014_x86_64 \
            --target=python \
            --implementation cp \
            --python-version 3.9 \
            --only-binary=:all: \
            --upgrade \
            -r requirements.txt
          zip -r layer.zip python

      - name: Upload Lambda Layer
        uses: actions/upload-artifact@v3
        with:
          name: lambda-layer
          path: backend/layer.zip

      - name: Deploy Lambda Layer
        run: |
          aws lambda publish-layer-version \
            --layer-name my-lambda-layer \
            --zip-file fileb://backend/layer.zip \
            --region ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
